name: Deploy website
on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
     
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cjecking to repo  
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashfiles('**/package-lock.json') }}
        
      - name: Install dependencies
        run: npm ci
        
      - name: testing the code
        run: npm run test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs: 
      scirpt-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: cjecking to repo  
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashfiles('**/package-lock.json') }}
      
      
      - name: Install dependencies
        run: npm ci
        
      - name: build the code
        run: npm run build
        
      - name: Publish artifacts
        id: publish 
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.j
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output the content
        run: ls
      - name: output file name
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: deploythe code
        run: echo "deploying the code"
        
        
      
        
        
         
