name: Deploy website
on:
  push:
    branches: [main]
  workflow_dispatch:
    branches: [main]
     
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm ci
        
      - name: testing the code
        run: npm run test
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
        
      - name: build the code
        run: npm run build
      
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            package.j
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: deploythe code
        run: echo "deploying the code"
        
        
      
        
        
         
